// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBXtdGnexRJM567gkk8IZjdT7JG6EnbOM',
    appId: '1:733389100645:web:5a57fc0dc491d64ac2188c',
    messagingSenderId: '733389100645',
    projectId: 'portfolio-310ae',
    authDomain: 'portfolio-310ae.firebaseapp.com',
    databaseURL: 'https://portfolio-310ae-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-310ae.appspot.com',
    measurementId: 'G-EX612HFKWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7XsP4SuT30e5mBk4FRJHLGUTmVjK2LLY',
    appId: '1:733389100645:android:0a5a7de6c0390151c2188c',
    messagingSenderId: '733389100645',
    projectId: 'portfolio-310ae',
    databaseURL: 'https://portfolio-310ae-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-310ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4fTxRJL6Hf1ZkZnZ6o-AFJRNE3LFIKb8',
    appId: '1:733389100645:ios:5e97943a5d72d2e3c2188c',
    messagingSenderId: '733389100645',
    projectId: 'portfolio-310ae',
    databaseURL: 'https://portfolio-310ae-default-rtdb.firebaseio.com',
    storageBucket: 'portfolio-310ae.appspot.com',
    iosClientId: '733389100645-q67rin15gg101psfl6bss5u1jq6bqj8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
